### PR TITLE
allow passing configurations to formidable

### PR DESCRIPTION
**Pull request by deanshub**
This allows passing down options for setting the rest of the formidable IncomingForm

### CODE REVIEW

**Comment by jaydenseric** [comment]
What formidable options in particular would you like to access?

My intention has been to abstract the multipart form parsing implementation so it can be swapped out without affecting the API.

**Comment by deanshub** [comment]
currently I need to use ```keepExtensions``` and ```maxFieldsSize```
but I think that in general this would be a nice addition, this doesn't break anything and gives more flexibility

**Comment by jaydenseric** [comment]
I doubt you need to use either of those.

Regarding `keepExtensions`, the resolver should move files out of the upload directory for permanent storage. The original filename, including the extension is available so the stored file can be named however you like.

`maxFieldsSize` does not relate to files, only the size of the JSON string of the graphql request (files extracted). You only need to worry about the 2MB default if your non-file variables are *massive*.

**Comment by jaydenseric** [comment]
Thanks for the PR, but closing this in favour of https://github.com/jaydenseric/apollo-upload-server/issues/13.

**Pull request closed without merging**
